---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Install python module and role dependencies
  - test -f requirements.txt && pip install -r requirements.txt
  - test -f requirements.yml && ansible-galaxy install -p tests/roles -r requirements.yml

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - set -e

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # run test
  - true && ! ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory --limit '!baidu.com'
  - ANSIBLE_REMOTE_PORT=80 ansible-playbook tests/test.yml -i tests/inventory
  - ANSIBLE_REMOTE_PORT=80 ansible-playbook tests/test.yml -i tests/inventory --become
  - true && ! ANSIBLE_REMOTE_PORT=11 ansible-playbook tests/test.yml -i tests/inventory
  - ANSIBLE_REMOTE_PORT=11 ansible-playbook tests/test.yml -i tests/inventory --limit '!baidu.com:!github.com' -e 'ansible_become=True'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
