---
- name: remote managing port should be reachable
  delegate_to: localhost
  vars:
  - inv_port: >-
      {{ hostvars[inventory_hostname].ansible_ssh_port
         | d(hostvars[inventory_hostname].ansible_port)
         | d(ansible_ssh_port)
         | d(ansible_port)
         | d }}
  - default_ports:
      ssh: 22
      winrm: "{{ (ansible_winrm_scheme | d('https') == 'https') | ternary(5986, 5985) }}"
      funcd: 51234
  - default_port: "{{ inv_conn | extract(default_ports) | d(22, True) }}"
  - inv_raw_conn: "{{ hostvars[inventory_hostname].ansible_connection | d('smart', True) }}"
  - inv_conn: >-
      {{ [ inv_raw_conn ]
         | intersect(['smart', 'paramiko', 'persistent'])
         | ternary('ssh', inv_raw_conn) }}
  - ansible_become: False
  - ansible_become_user: "{{ lookup('id', 'uname') }}"
  when: ([ inv_conn ]) | intersect(['ssh', 'winrm', 'funcd'])
  wait_for:
    host: >-
      {{ hostvars[inventory_hostname].ansible_ssh_host
         | d(hostvars[inventory_hostname].ansible_host, True)
         | d(inventory_hostname, True) }}
    port: >-
      {{ [ inv_conn ]
         | intersect(['funcd'])
         | ternary(default_port, inv_port | d(default_port, True)) }}
    state: started
    connect_timeout: 2
    timeout: 2
