---
- name: ssh port should be reachable
  connection: local
  wait_for:
    host: "{{ ansible_host | d(inventory_hostname) }}"
    port: "{{ ansible_port | d(local_ansible_config['defaults/remote_port']) | d(22) }}"
    state: started
    connect_timeout: 2
    timeout: 2
